stages:
  - deploy_prod

.image: &image_deploy_jobs
  image: grewn0uille/deploy-tools:latest

deploy_prod:
  <<: *image_deploy_jobs
  stage: deploy_prod
  script:
    - make deploy-prod
  dependencies: []
  only:
    - master
